apiVersion: apps/v1
kind: Deployment
metadata:
  name: # [owner]-[title]-[action]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: # [owner]-[title]-[action]
  template:
    metadata:
      labels:
        app: # [owner]-[title]-[action]
    spec:
      containers:
        - name: # [owner]-[title]-[action]
          image: # gcr.io/[project]/[owner]_[title]_tasks:[tag]
          imagePullPolicy: Always
          command: [] # ["./celery_[action].sh"]
          args: [] # ["[owner]", "[title"]
          resources:
            requests:
              memory:
              cpu:
            limits:
              memory:
              cpu:
          env:
            - name: OUTPUTS_VERSION
              value: v1
            - name: CS_URL
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: CS_URL
      nodeSelector:
        component: model