apiVersion: apps/v1
kind: Deployment
metadata:
  name: outputs-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outputs-processor
  template:
    metadata:
      labels:
        app: outputs-processor
    spec:
      containers:
        - name: outputs-processor
          image:
          ports:
            - containerPort: 8888
          env:
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: BUCKET
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_DB
                  optional: true
            - name: REDIS_USER
              value: outputs
            - name: REDIS_PW
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: REDIS_OUTPUTS_PW
            - name: CS_CRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: CS_CRYPT_KEY
      nodeSelector:
        component: api
