version: '3'
services:
  flask:
    image: "comp/flask:${TAG}"
    ports:
      - 5050:5050
    depends_on:
      - redis
      # Add celery workers here:
      # - {project_name}_tasks
      - compbaseball_tasks
  # configure celery workers:
  # {project_name}_tasks:
  #   image: "comp/{project_name}_tasks:${TAG}"
  #   depends_on:
  #     redis
  compbaseball_tasks:
    image: "comp/compbaseball_tasks:${TAG}"
    depends_on:
      - redis
  redis:
    image: redis
